name: Build with PyInstaller

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  pyinstaller-build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            artifact: Bethini-linux
          - os: macos-latest
            artifact: Bethini-darwin
          - os: windows-latest
            artifact: Bethini-windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install Linux GUI libraries
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            tcl tk tcl-dev tk-dev \
            libx11-dev libxext-dev libxrender-dev libxft-dev libxss-dev

      - name: Setup Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: pyinstaller bethini_onefile.spec

      - name: Copy additional files
        run: python .github/scripts/copy_dist_files.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: ${{ matrix.artifact }}
          path: dist
